name: parking
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  drift: ^1.5.0
  sqlparser: ^0.21.0 
  path_provider: ^2.0.9
  sqflite:
  sqlite3_flutter_libs: ^0.5.4
  equatable: ^2.0.3
  json_serializable: ^6.1.5
  dartz: ^0.10.1
  flutter_bloc: ^8.0.1
dev_dependencies:
  bloc_test: ^9.0.2
  build_runner: ^2.1.8
  drift_dev: ^1.5.1
  mocktail: ^0.2.0  
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
